@startuml
class Student{
    - String name
    - String surname
    - String id
    - float grade

    + void setGrade(float grade)
    + float getGrade()
    + String getName()
    + void setName(String name)
    + String getSurname()
    + void setSurname(String surname)
    + String getId()
    + void setId(String id)


}

class Subject{
    - String name
    - Student[] students
    - boolean isOrdered
    - int position
    - int capacity

    + void addStudent(Student student)
    + void orderStudents()
    + double getAverage()
    + float getMedian()
    + int getPosition()
    + Student getBestStudent()
    + Student getWorstStudent()

}
@enduml