@startuml
class BankAccount {
    - String user
    - double amount
    + BankAccount(String user, double amount)
    + String getTitular()
    + void setTitular(user: String)
    + double getCantidad()
    + void setCantidad(quantity: double)
    + void deposit(quantity: double)
    + void withdraw(quantity: double)
}
@enduml