@startuml

class Student {
    + name
    + surname
    + id
    + grade

    - getName()
    - setName()
    - getSurname()
    - setSurname()
    - getId()
    - setId()
    - getGrade()
    - setGrade()
}

@enduml