@startuml
class BankAccount {
  ~String holder
  ~double amount
  
  +BankAccount(String holder, double amount)

  +String getHolder()
  +void setHolder(String holder)
  +double getAmount()
  +void setAmount(double amount)
  
  +void deposit(double amount)
  +void withdraw(double amount)
}
@enduml