@startuml
class User{
    +userName: String
    +password: String
    +name:String
    +options:Option

    +User()
    +User(userName,password,name)
    +getUserName()
    +setUserName(userName)
    +getPassword()
    +setPassword(password)
    +getName()
    +setName(name)
    +getOptions()
    +tryPassword(passwordTried)
    +setOptions(options)
}

@enduml