@startuml
class User {
    -userName: String
    -userPassword: String
    +login: boolean
    +User()
    +User(String userName, String userPassword)
    +setUserName(String)
    +setUserPassword(String)
    +getUserName(): String
    +getUserPassword(): String
    +setLogin(boolean)
    +getLogin(): boolean
}
@enduml