@startuml
class Option{
    + isLoggedIn: boolean

    - getIsLoggedIn(): boolean
    - SetIsLoggedIn(isLoggedIn: boolean): void
    - Option()
    - changePassword(): void
    - changeUsername(): void
    - logOut(): void
}
@enduml