@startuml
folder main {
    class Main {
        +Enigma enigma
        +UserDataBase userDataBase
        +Manager manager(userDataBase)
        +static main(): void
    }
    package Utils {
        package Interfaces {
            interface MenuItem {
                String getText()
                void execute()
            }
        }
        package Enums {
            enum Subjects {
                PROGRAMMING_II("Programming II"),
                MATHEMATICS_II("Mathematics II"),
                LOGIC("Logic"),
                DISCRETE_MATHEMATICS("Discrete Mathematics"),
                ICT("ICT"),
            }
        }
    }

    package Classes {
        package Menu {
            class Options {
                -final MenuItem quit
                -final MenuItem logout
                -final Scanner scanner
                -final MenuItem[] studentOptions
                -final MenuItem[] teacherOptions
                -final MenuItem[] adminOptions
                -logout(): void
                -quit(): void
                -displayGrades(): void
                -studentSendEmail(): void
                -validateSubject(String): boolean
                -getSubjectTeacher(String): String
                -displayAllStudentGrades(): void
                -getGrades(Student student, Subject teacherSubject): int
                -changeStudentGrade(): void
                -validateStudent(String): boolean
                -displayAllUsers(): boolean
                -editUser(String operationType): void
                -validateUser(int selectedUserIndex, User[] users): User
                -getEnigmaKey(): void
                -getStudentOptions(): MenuItem[]
                -getAdminOptions(): MenuItem[]
                -getTeacherOptions(): MenuItem[]
                +getSelectedUserOptions(): MenuItem[]
            }
            class MenuItemImpl implements main.Utils.Interfaces.MenuItem {
                -final String text
                -final Runnable action
                +MenuItemImpl(String text, Runnable action)
                +getText(): String
                +execute(): void
            }
        }
        package Users {
            abstract class User {
                #String username
                #String password;
                #boolean login
                +User(String username, String password, boolean login)
                +setUsername(String userName): void
                +setPassword(String password): void
                +setLogin(): void
                +getUsername(): String
                +getPassword(): String
                +isLogin(): boolean
            }
            class Student extends User {
                -String[] subjects
                -int[] grades
                +Student(String username, String password, int[] grades)
                +getGrades(): int[]
                +setGrade(int index, int newGrade)
                +getSubjects(): Subjects[]
            }
            class Teacher extends User {
                -final Subjects subject
                +Teacher(String username, String password, Subjects subject)
                +getSubject(): Subjects
            }
            class Admin extends User {
                +Admin(String userName, String password)
            }
        }
        class Enigma {
            -static ArrayList<Character> list;
            -static ArrayList<Character> shuffledList
            -static char character;
            +Enigma()
            -static newKey(): void
            +static getKey(): void
            +static encrypt(String password): String
            +static decrypt(String password): String
        }

        class Manager {
            +static boolean runSystem
            +static User currentUser
            +static User[] users
            -final Scanner scanner
            -final Options options
            +Manager(User[] users)
            +login(): void
            +validateUserName(String userName): boolean
            +validatePassword(String password): boolean
            +getValidatedUser(String userName): User
            +displayOptions(): void
        }
        class UserDataBase {
            -final users
            +UserDataBase()
            +getUsers(): User[]
        }
    }
    Main --*  Manager : requires
    Main --*  UserDataBase : requires
    Main --*  Enigma : requires
    UserDataBase --*  User : requires
    Student --o main.Utils.Enums.Subjects : has
    Teacher --o main.Utils.Enums.Subjects : has
    Manager --* Options : requires
    Options --*  main.Utils.Interfaces.MenuItem : requires
}

@enduml