@startuml
class Student {
    - String name
    - String surname
    - String id
    - float grade
    + Student(String name, String surname, String id, float grade)
    + getName()
    + setName(String name)
    + getSurname()
    + setSurname(String surname)
    + getId()
    + setId(String id)
    + getGrade()
    + setGrade(float grade)
}
@enduml